import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(418, 190)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.center()
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 641, 281))
        self.stackedWidget.setObjectName("stackedWidget")
        self.config_page = QtWidgets.QWidget()
        self.config_page.setObjectName("config_page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.config_page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 401, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.url_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.url_label.setObjectName("url_label")
        self.gridLayout.addWidget(self.url_label, 2, 0, 1, 1)
        self.Exit = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.Exit.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.Exit.setObjectName("Exit")
        self.gridLayout.addWidget(self.Exit, 5, 0, 1, 2, QtCore.Qt.AlignRight)
        self.refreshes_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.refreshes_label.setObjectName("refreshes_label")
        self.gridLayout.addWidget(self.refreshes_label, 3, 0, 1, 1)
        self.browser_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.browser_label.setObjectName("browser_label")
        self.gridLayout.addWidget(self.browser_label, 1, 0, 1, 1)
        self.interval_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.interval_label.setObjectName("interval_label")
        self.gridLayout.addWidget(self.interval_label, 4, 0, 1, 1)
        self.refreshes_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.refreshes_spinbox.setMinimum(1)
        self.refreshes_spinbox.setMaximum(1000)
        self.refreshes_spinbox.setObjectName("refreshes_spinbox")
        self.gridLayout.addWidget(self.refreshes_spinbox, 3, 1, 1, 1)
        self.interval_spinbox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.interval_spinbox.setMinimum(1)
        self.interval_spinbox.setMaximum(100)
        self.interval_spinbox.setObjectName("interval_spinbox")
        self.gridLayout.addWidget(self.interval_spinbox, 4, 1, 1, 1)
        self.url_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.url_edit.setObjectName("url_edit")
        self.gridLayout.addWidget(self.url_edit, 2, 1, 1, 1)
        self.browser_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.browser_combobox.setObjectName("browser_combobox")
        self.browser_combobox.addItem("")
        self.browser_combobox.addItem("")
        self.browser_combobox.addItem("")
        self.gridLayout.addWidget(self.browser_combobox, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.config_page)
        self.blitz_page = QtWidgets.QWidget()
        self.blitz_page.setObjectName("blitz_page")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.blitz_page)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 401, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.num_refreshes_left = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.num_refreshes_left.setObjectName("num_refreshes_left")
        self.gridLayout_2.addWidget(self.num_refreshes_left, 0, 0, 2, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber.setToolTip("")
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setProperty("value", 1.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 1, 2, 1)
        self.abort_blitz = QtWidgets.QDialogButtonBox(self.gridLayoutWidget_2)
        self.abort_blitz.setAutoFillBackground(False)
        self.abort_blitz.setStandardButtons(QtWidgets.QDialogButtonBox.Abort)
        self.abort_blitz.setCenterButtons(True)
        self.abort_blitz.setObjectName("abort_blitz")
        self.gridLayout_2.addWidget(self.abort_blitz, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.blitz_page)
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def center(self):
        frameGm = self.frameGeometry()
        screen = QtWidgets.QApplication.desktop().screenNumber(QtWidgets.QApplication.desktop().cursor().pos())
        centerPoint = QtWidgets.QApplication.desktop().screenGeometry(screen).center()
        frameGm.moveCenter(centerPoint)
        self.move(frameGm.topLeft())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trophy Blitz"))
        self.url_label.setText(_translate("MainWindow", "URL: "))
        self.refreshes_label.setText(_translate("MainWindow", "Refreshes: "))
        self.browser_label.setText(_translate("MainWindow", "Default Browser: "))
        self.interval_label.setText(_translate("MainWindow", "Interval (min): "))
        self.url_edit.setPlaceholderText(_translate("MainWindow", "https://www.google.com"))
        self.browser_combobox.setItemText(0, _translate("MainWindow", "Firefox"))
        self.browser_combobox.setItemText(1, _translate("MainWindow", "Chrome"))
        self.browser_combobox.setItemText(2, _translate("MainWindow", "Edge"))
        self.num_refreshes_left.setText(_translate("MainWindow", "Opened 5/10 pages."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
